In [4]:
import numpy as np

nums = [1,2,3,4]

# nums + 5

nums_2 =  np.array([1,2,3,4])
print(nums_2)
new_num = 5
print(5)
new_nums = nums_2 + new_num
print(new_nums)

[1 2 3 4]
5
[6 7 8 9]


In [6]:
a  = np.array([[1,2,3], [1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [8]:
b= 2
c = a + b
c

array([[3, 4, 5],
       [3, 4, 5]])

In [10]:
a = np.array([[1,2,3],[4,5,6]])
b =np.array([7,8,9])
c = a + b
print(c)

[[ 8 10 12]
 [11 13 15]]


In [12]:
a = np.array([[1,2,3],[4,5,6]])
b =np.array([7,8,9])
c = a + b


In [14]:
months = ['January','February','March',"April", "May",'June']

for index,month in enumerate(months):
  print(f'{index} - {month}')

0 - January
1 - February
2 - March
3 - April
4 - May
5 - June
