# Hello

In [1]:
import numpy as np

In [2]:
mtrx = np.arange(64).reshape(8,8)
print(mtrx)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]


In [3]:
mtrx = np.matrix([[0,0],[0,0]])
mtrx

matrix([[0, 0],
        [0, 0]])

In [4]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
def reverse_array(arr, copy=True):
  if copy:
    arr = arr.copy()
  mid = len(arr) // 2
  for i in range(mid):
    arr[i],arr[-i-1] = arr[-i-1],arr[i]
  return arr


In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
reversed = reverse_array(arr)

In [8]:
reversed

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [9]:
reverse_array(np.array([1,2,3,4]))

array([4, 3, 2, 1])

In [10]:
reverse_array(np.array([1,2,3]))

array([3, 2, 1])

In [11]:
new_arr = np.array([1,2,3,4])[:]

In [12]:
new_arr

array([1, 2, 3, 4])

In [13]:
newer = new_arr[:]

In [14]:
newer

array([1, 2, 3, 4])

In [18]:
newer == new_arr

array([ True,  True,  True,  True])

In [16]:
newer is new_arr

False

In [17]:
newer[0] = 99

In [19]:
newer

array([99,  2,  3,  4])

In [20]:
new_arr

array([99,  2,  3,  4])

In [21]:
def run_tests():

  # test 1
  some_arr = np.array([1,2,3,4])
  new_arr = some_arr[:]
  assert some_arr is not new_arr
  some_arr[0] = 999
  assert new_arr[0] != 1


  # test 2
  some = np.array([1,2,3,4])
  other = some.view()
  some[0] = 999
  assert other[0] == 999


  # test 3
  some = np.array([1,2,3,4])
  other = some.copy()
  some[0] = 999
  assert other[0] == 1
  
  print('........ SUCCESS .........')

In [22]:
run_tests()

........ SUCCESS .........


In [23]:
some = np.array([5,6,7,8])
other = np.array(some)
some[0] = 55
other

array([5, 6, 7, 8])

# Buy Low Sell High

In [24]:
prices = np.full(100, fill_value=np.nan)
prices[[0, 25, 60, -1]] = [80., 30., 75., 50.]

In [25]:
prices

array([80., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 30.,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 75., nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 50.])