In [1]:
import numpy as np

In [2]:
mat = np.zeros((8,8), dtype="int")
print(mat)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [3]:
mat[3][6] = 1
mat

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
# 1 in mat[6]
# 1 in mat.transpose()[6]

In [5]:
def in_column(grid, col, value):
  return value in grid.transpose()[col]

In [6]:
# tests
success = '........ ALL TESTS PASSED ........'
assert in_column(mat, 6, 1) == True
print(success)

........ ALL TESTS PASSED ........


In [7]:
np.empty((3,3))

array([[ 2.60605835e-31, -5.21211670e-31,  1.30302917e-31],
       [-5.21211670e-31,  1.13363538e-30, -3.51817877e-31],
       [ 1.30302917e-31, -3.51817877e-31,  2.01969522e-31]])

In [8]:
np.empty((3,3),dtype=np.int)

array([[4149262842402738779, 4153766442030109281, 4144759242775368305],
       [4153766442030109280, 4158790770364394495, 4151345757230397662],
       [4144759242775368297, 4151345757230397654, 4147923825727815228]])

In [9]:
np.full((3,3), True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])